### ISSUE TITLE
NameError: uninitialized constant LogStasher::ActiveRecord

### ISSUE THREAD

**Issue by bastoune** [shadabahmed/logstasher#141]
I added the gemfile and the `logstaher.yml` file (also tried with the lined in `application.rb`) as specified
But I got this error from unicorn 

 ```
==> /home/mushin-api/unicorn/log/unicorn.stdout.log <==
bundler: failed to load command: unicorn (/home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/bin/unicorn)
```

```==> /home/mushin-api/unicorn/log/unicorn.stderr.log <==
NameError: uninitialized constant LogStasher::ActiveRecord
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/logstasher-1.2.1/lib/logstasher.rb:96:in `setup_before'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/logstasher-1.2.1/lib/logstasher/railtie.rb:34:in `block in <class:Railtie>'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/initializable.rb:30:in `instance_exec'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/initializable.rb:30:in `run'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/initializable.rb:54:in `run_initializers'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/application.rb:352:in `initialize!'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/railtie.rb:194:in `public_send'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/railtie.rb:194:in `method_missing'
  /home/mushin-api/mushin-api/source/config/environment.rb:6:in `<top (required)>'
  config.ru:5:in `require'
  config.ru:5:in `block in <main>'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn.rb:56:in `eval'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn.rb:56:in `block in builder'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:752:in `build_app!'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:129:in `start'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/bin/unicorn:126:in `<top (required)>'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
  /home/mushin-api/mushin-api/source/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<top (required)>'
```

**Comment by natematykiewicz** [comment]
Sounds like you have ActiveRecord logging enabled, but don't have ActiveRecord installed. Are you using ActiveRecord? If not, set `config.logstasher.record_enabled = false`.
