### ISSUE TITLE
Elasticsearch cannot accept documents within arrays (or so)

### ISSUE THREAD

**Issue by ernetas** [shadabahmed/logstasher#67]
If, for example, logstasher generates this log line (real numbers replaced with 0es for privacy):

```
{"@source":"unknown","@tags":["request"],"@fields":{"method":"POST","path":"/0/","format":"*/*","controller":"0/0","action":"update","status":200,"duration":100.1,"view":0.2,"db":25.75,"ip":"0.0.0.0","route":"0/0#0","request_id":"30af3016-8f26-4764-8a48-bf3e201c7492","parameters":{"cells":{"c;0;0;2015-02-03":["w",[{"rt":"g","ri":0,"id":0},{"rt":"r","ri":0,"id":0,"amt":0},{"rt":"w","st":0,"et":0,"color":"0","description":null,"breaks":0,"amt":0}]]},"pp":0,"ctx_token":"0"},"client_id":0,"shop_id":0,"user_id":0,"site":"app"},"@timestamp":"2015-02-03T14:48:31.588Z","@version":"1","type":"rails","file":"/home/deployer/apps/xxx/shared/log/logstash_lol.log","host":"in2","offset":"104057368"}
```

It will not be accepted by Elasticsearch and it will throw an exception:

```
[2015-02-03 18:49:13,963][DEBUG][action.bulk              ] [X-Man] [logstash-2015.02.03][1] failed to execute bulk item (index) index {[logstash-2015.02.03][rails][1SZRSpULSwW4-FHNwwORSQ], source[{"@source":"unknown","@tags":["request"],"@fields":{"method":"POST","path":"/0/","format":"*/*","controller":"0/0","action":"update","status":200,"duration":100.1,"view":0.2,"db":25.75,"ip":"0.0.0.0","route":"0/0#0","request_id":"30af3016-8f26-4764-8a48-bf3e201c7492","parameters":{"cells":{"c;0;0;2015-02-03":["w",[{"rt":"g","ri":0,"id":0},{"rt":"r","ri":0,"id":0,"amt":0},{"rt":"w","st":0,"et":0,"color":"0","description":null,"breaks":0,"amt":0}]]},"pp":0,"ctx_token":"0"},"client_id":0,"shop_id":0,"user_id":0,"site":"app"},"@timestamp":"2015-02-03T14:48:31.588Z","@version":"1","type":"rails","file":"/home/deployer/apps/xxx/shared/log/logstash_lol.log","host":"in2","offset":"24970"}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [@fields.parameters.cells.c;0;0;2015-02-03]
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:415)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:555)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeNonDynamicArray(ObjectMapper.java:686)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeArray(ObjectMapper.java:605)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeNonDynamicArray(ObjectMapper.java:688)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeArray(ObjectMapper.java:605)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:492)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:555)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:490)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:555)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:490)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:555)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:490)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:541)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:490)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:392)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:444)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:150)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:511)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: unknown property [rt]
        at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateFieldForString(StringFieldMapper.java:331)
        at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateField(StringFieldMapper.java:277)
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:405)
        ... 22 more
```

**Comment by Sija** [comment]
If my eyes serves me right than there's a syntax error in `@fields.parameters.cells.c` key definition.
Offending part: `{"cells":{"c;0;0;2015-02-03":`

**Comment by ernetas** [comment]
@Sija that's correct, but:
```
 ruby {
     code => [ "if event['@fields'] and event['@fields'].include?('parameters'); event['@fields']['parameters'] = event['@fields']['parameters'].to_s; end" ]
   }
   geoip {
     source => "[@fields][ip]"
   }
```
Should take care of this, no?

**Comment by Sija** [comment]
Seems to me like the `event['@fields']['parameters']` hash is coming in already "broken" (i.e. with malformed `c` key)

**Comment by ernetas** [comment]
Okay... In that case, how could I take care of that?
