### ISSUE TITLE
Logstasher not logging RoutingError

### ISSUE THREAD

**Issue by chongivan** [shadabahmed/logstasher#84]
Hi there,

In **production.log** i have:
```
ActionController::RoutingError (No route matches [GET] "/asdf"):
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
```

However this is not reflected in **logstash_production.log**.

Best,
Ivan

**Comment by recipedude** [comment]
Also noticed this issue.  Error logging is important.
